version: '2'
services:
  peer-base:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_default
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # The following setting skips the gossip handshake since we are
      # are not doing mutual TLS
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_CHAINCODE_STARTUPTIMEOUT=600s
      - CORE_CHAINCODE_DEPLOYTIMEOUT=600s

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start 
    volumes:
        - /var/run/:/host/var/run/

  zookeeper0.example.com:
    container_name: zookeeper0.example.com
    extends:
      file: kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  zookeeper1.example.com:
    container_name: zookeeper1.example.com
    extends:
      file: kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888

  zookeeper2.example.com:
    container_name: zookeeper2.example.com
    extends:
      file: kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888

  kafka0.example.com:
    container_name: kafka0.example.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
    ports:
      - 9092:9092
      - 9093:9093

  kafka1.example.com:
    container_name: kafka1.example.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    ports:
      - 10092:9092
      - 10093:9093

  kafka2.example.com:
    container_name: kafka2.example.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    ports:
      - 11092:9092
      - 11093:9093

  kafka3.example.com:
    container_name: kafka3.example.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    ports:
      - 12092:9092
      - 12093:9093
